name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.28+1
  flutter_launcher_icons: ^0.7.3


  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  modal_progress_hud: ^0.1.3
  razorpay_flutter : ^1.1.1
  fluttertoast: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_icons: ^1.1.0
  android: 'launcher_icon'
  image_path: 'images/mylogo1.png'

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
    - family: Dancing Script
      fonts:
        - asset: fonts/DancingScript-Bold.ttf
