name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.28+1
  flutter_launcher_icons: ^0.7.3


  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.0
  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  modal_progress_hud: ^0.1.3
  razorpay_flutter : ^1.1.1
  fluttertoast: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  image_path: 'images/mylogo1.png'

flutter:
  uses-material-design: true

  assets:
  - images/one.jpg
  - images/edu.jpg
  - images/senior.jpg
  - images/blood.jpg
  - images/clothes1.jpg
  - images/food.jpg
  - images/wash.jpg
  - images/ce2.jpg
  - images/ce6.png
  - images/ce4.jpg
  - images/ce5.jpg
  - images/ce7.jpg
  - images/ce8.jpg
  - images/ce9.png
  - images/ce10.jpg
  - images/ce1.jpg
  - images/ce3.jpg
  - images/PicsArt_05-29-01.32.33.png
  - images/b1.jpg
  - images/b2.png
  - images/b3.jpg
  - images/b4.jpg
  - images/b5.jpg
  - images/b6.jpg
  - images/b7.png
  - images/a1.jpg
  - images/a2.jpg
  - images/a3.jpg
  - images/a4.jpg
  - images/a5.jpg
  - images/a6.jpg
  - images/a7.jpg
  - images/mylogo1.png
  - images/d1.jpg
  - images/d2.png


  fonts:
    - family: Dancing Script
      fonts:
        - asset: fonts/DancingScript-Bold.ttf
